-- Migration: create projeto_ativ_ia table + RLS
-- Target: Supabase Postgres (public schema)

begin;

create table if not exists public.projeto_ativ_ia (
  cod_ativ_ia bigint generated by default as identity primary key,
  cod_ativ_equipe int not null,
  data_acao date not null,
  hora_acao time not null,
  info jsonb not null,
  constraint projeto_ativ_ia_cod_ativ_equipe_positive check (cod_ativ_equipe > 0),
  constraint projeto_ativ_ia_info_has_cod_ativ_equipe check (info ? 'cod_ativ_equipe'),
  constraint projeto_ativ_ia_info_cod_ativ_equipe_matches check (
    (info->>'cod_ativ_equipe') ~ '^[0-9]+$'
    and ((info->>'cod_ativ_equipe')::int = cod_ativ_equipe)
  )
);

create index if not exists idx_projeto_ativ_ia_equipe_data_hora
  on public.projeto_ativ_ia (cod_ativ_equipe, data_acao, hora_acao);

alter table public.projeto_ativ_ia enable row level security;

-- Policies: authenticated users can insert/select.
drop policy if exists "projeto_ativ_ia_insert_authenticated" on public.projeto_ativ_ia;
create policy "projeto_ativ_ia_insert_authenticated"
  on public.projeto_ativ_ia
  for insert
  to authenticated
  with check (true);

drop policy if exists "projeto_ativ_ia_select_authenticated" on public.projeto_ativ_ia;
create policy "projeto_ativ_ia_select_authenticated"
  on public.projeto_ativ_ia
  for select
  to authenticated
  using (true);

commit;

-- Verification queries (execute manually in Supabase SQL editor)
-- 1) OK insert
-- insert into public.projeto_ativ_ia (cod_ativ_equipe, data_acao, hora_acao, info)
-- values (10, current_date, current_time, jsonb_build_object('cod_ativ_equipe', 10, 'msg', 'teste'));
--
-- 2) FAIL: missing cod_ativ_equipe in info
-- insert into public.projeto_ativ_ia (cod_ativ_equipe, data_acao, hora_acao, info)
-- values (10, current_date, current_time, jsonb_build_object('msg', 'teste'));
--
-- 3) FAIL: mismatch cod_ativ_equipe
-- insert into public.projeto_ativ_ia (cod_ativ_equipe, data_acao, hora_acao, info)
-- values (10, current_date, current_time, jsonb_build_object('cod_ativ_equipe', 11));
